### ISSUE TITLE
gives me many errors

### ISSUE THREAD

**Issue by michaelkremenetsky** [Sunney-X/SurveyBOT#7]
Login of Twilio was successful...
Proceeding with the program
Traceback (most recent call last):
  File "SurveyBOT.py", line 68, in credentialCheck
    with open("credentials.json") as key:
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michael\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "SurveyBOT.py", line 220, in <module>
    checkList()
  File "SurveyBOT.py", line 59, in checkList
    credentialCheck()
  File "SurveyBOT.py", line 82, in credentialCheck
    create_new_number(acid, act)
  File "SurveyBOT.py", line 110, in create_new_number
    smsCheck(numberf, id, token)
  File "SurveyBOT.py", line 129, in smsCheck
    c = webdriver.Firefox()
  File "C:\Users\Michael\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\Michael\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by michaelkremenetsky** [comment]
fixed the gecko driver stuff gives me this now

Traceback (most recent call last):
  File "surveyBOT.py", line 3, in <module>
    from twilio.rest import Client
  File "C:\Users\Michael\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\twilio\rest\__init__.py", line 14, in <module>
    from twilio.http.http_client import TwilioHttpClient
  File "C:\Users\Michael\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\twilio\http\http_client.py", line 1, in <module>
    from requests import Request, Session, hooks
  File "C:\Users\Michael\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\Michael\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "C:\Users\Michael\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\urllib3\connectionpool.py", line 7, in <module>
    from socket import error as SocketError, timeout as SocketTimeout
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\socket.py", line 49, in <module>
    import _socket
ImportError: Module use of python36.dll conflicts with this version of Python.
